### ISSUE TITLE
TODO's 

### ISSUE THREAD

**Issue by JonasBerx** [AutomatedProcessImprovement/roptimus-prime#1]
# Optimus TODO list

#### Optimus prime wants to be more efficient, here's some tasks that need to happen:

- [x] Additional constraints for datastructure
- - Time start of day
- - Time end of day OR hours in working day
- - Resource limit on hours per week (sum of bitmaps)

- [x] RosterManager
- [x] API: How much cap left | For day | For Resource | ...
- [ ] HC / NGSA
- [x] Redo bitmaps instead of array to binary number
- [ ] Set up experiments

**Comment by JonasBerx** [comment]
New things to do:
- IterationHandler needs updated import from update_1
- Majority of functions in Hill climb need updated functions called so that we dont change the # of resources in pool but rather generate a new timetable for that resource

**Comment by JonasBerx** [comment]
Minor bug; in getaccessible bits, search should work with just "RESOURCENAME" and not "RESOURCENAMEtimetable" - Resolved
